name: Pull Request
on: pull_request

env:
  SLN_FILE: Fabulous.MauiControls.MediaElement.NoSamples.sln
  CONFIG: Release

jobs:
  pull_request:
    runs-on: macos-12
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Check code formatting
      run: |
        dotnet tool restore
        dotnet fantomas --check -r src samples templates
    - name: Install dotnet workload
      run: dotnet workload install maui
    - name: Restore
      run: dotnet restore ${SLN_FILE}
    - name: Build
      run: dotnet build ${SLN_FILE} -c ${CONFIG} --no-restore
    - name: Test
      run: dotnet test ${SLN_FILE} -c ${CONFIG} --no-build